Create private VCs on-demand
LilyWonhalf/NostradamusDiscordBot pull request #28
Opened 2020-11-10 21:45 UTC by SpecialFlocon

WIP

2020-11-10 21:56 UTC, LilyWonhalf approved these changes

2020-11-23 01:02 UTC, LilyWonhalf requested changes

2020-11-23 01:02 UTC, LilyWonhalf commented on event/bot/voiceStateUpdate.js
> +            await Promise.all([
The content of the "if"s should be in private-vc.js
smallVoiceChatRequestHandler()

2020-11-23 01:02 UTC, LilyWonhalf commented on event/bot/voiceStateUpdate.js
> +            const privateChannel = oldVoiceState.channel;
The content of the "if"s should be in private-vc.js
smallVoiceChatLeftHandler()

2020-11-23 10:13 UTC, SpecialFlocon commented on event/bot/voiceStateUpdate.js
> +            const privateChannel = oldVoiceState.channel;
Done in 0d3222d

2020-11-23 10:13 UTC, SpecialFlocon commented on event/bot/voiceStateUpdate.js
> +            await Promise.all([
Done in 0d3222d

2020-11-24 08:30 UTC, LilyWonhalf approved these changes
Il y a un commentaire non bloquant, tu peux quand même faire la modification (ou argumenter contre).

Je vais pas le merger de suite, je vais tester quand j'aurai le temps et si tout fonctionne je pourrai merger.

Merci beaucoup !

2020-11-24 08:30 UTC, LilyWonhalf commented on model/private-vc.js
> +            member.guild.channels.create("[Waiting room] ⬆️", {
Je mettrais l'emoji sur la gauche, ou au moins des deux côtés, parce que des fois l'écran est trop petit et ça masque les caractères qui sont à droite 👀

2020-11-24 14:53 UTC, SpecialFlocon commented on model/private-vc.js
> +            member.guild.channels.create("[Waiting room] ⬆️", {
En fait, j'irais même plus loin en retirant `[Private]` et en remplaçant `[Waiting room]` par ⌚.

2020-12-20 21:02 UTC, LilyWonhalf commented on model/private-vc.js
> +            member.guild.channels.create("[Waiting room] ⬆️", {
Non 👀

2020-12-20 21:02 UTC, LilyWonhalf commented on model/private-vc.js
> +            member.guild.channels.create("[Waiting room] ⬆️", {
Tu peux rajouter l'emoji devant si tu veux par contre

2020-12-20 23:29 UTC, LilyWonhalf commented
Fonctionnalités manquantes : 

- Salon textuel lié
- Question pour salon public ou privé ?
- Si salon privé
	- Waiting room
	- Quand quelqu'un rejoint la waiting room, envoyer message dans salon textuel lié "XX veut rejoindre" avec des réactions pour oui et non
- Suppression de la waiting room

2021-01-05 00:02 UTC, SpecialFlocon commented on model/private-vc.js
> +                    PrivateVC.list[requestor].pop();
Can't remember what's this for, seems like a mistake?

2021-01-05 00:49 UTC, LilyWonhalf requested changes

2021-01-05 00:49 UTC, LilyWonhalf commented on bot.js
> +    global.perCategoryChannelLimit = 50;
global.channelPerCategoryLimit

2021-01-05 00:49 UTC, LilyWonhalf commented on model/private-vc.js
> +            if (exception.payload) {
Spaces around blocks

2021-01-05 00:49 UTC, LilyWonhalf commented on model/private-vc.js
> +        const embed = new Discord.MessageEmbed().addFields([
```js
        const embed = new Discord.MessageEmbed()
            .addFields([
                {name: '🔓', value: trans('model.privateVC.channelType.public'), inline: true},
                {name: '🔒', value: trans('model.privateVC.channelType.private'), inline: true},
            ])
            .setTitle(trans('model.privateVC.channelType.embed.title'))
            .setFooter(trans('model.privateVC.channelType.embed.footer'))
            .setColor(0x00FF00);
        
        const sentMessage = await textChannel.send({content: member, embed: embed});
```

2021-01-05 09:06 UTC, SpecialFlocon commented on bot.js
> +    global.perCategoryChannelLimit = 50;
18c13fd

2021-01-05 09:06 UTC, SpecialFlocon commented on model/private-vc.js
> +            if (exception.payload) {
18c13fd

2021-01-05 09:06 UTC, SpecialFlocon commented on model/private-vc.js
> +        const embed = new Discord.MessageEmbed().addFields([
18c13fd

2021-01-05 11:48 UTC, SpecialFlocon commented
TODO:

- Lock/unlock VC request channel command
- *Emergency exit/pull the plug* command

2021-01-05 22:44 UTC, LilyWonhalf requested changes

2021-01-05 22:44 UTC, LilyWonhalf commented on model/command/private-vc.js
> +class PrivateVc
PrivateVC

2021-01-05 22:44 UTC, LilyWonhalf commented on model/command/private-vc.js
> +            switch (action) {
You're missing a "default" in which you tell the mod that the action is unknown

2021-01-05 22:50 UTC, SpecialFlocon commented on model/command/private-vc.js
> +class PrivateVc
cf8581b

2021-01-05 22:50 UTC, SpecialFlocon commented on model/command/private-vc.js
> +            switch (action) {
cf8581b

2021-01-05 22:51 UTC, LilyWonhalf submitted a review, later dismissed

2021-01-08 13:58 UTC, merged