Feature/#80 event iwd
LilyWonhalf/NostradamusDiscordBot pull request #64
Opened 2021-02-25 16:26 UTC by julienChemin

2021-02-25 16:46 UTC, julienChemin commented on model/command/pick-winners.js
> +        this.isAllowedForContext = CommandPermission.isMemberModOrSoftOrAnimator;//isMommy;//TODO
👍

2021-02-28 21:56 UTC, LilyWonhalf requested changes

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/pick-winners.js
> +                }
`lotteryBox = lotteryBox.concat(new Array(memberAppliedTokens.amount_applied).fill(member.user));`

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/pick-winners.js
> +        for (let i = 0; i < amountToPick; i++) {
`const winners = new Array(amountToPick).map(() => {`

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/pick-winners.js
> +            lotteryBox = lotteryBox.filter(token => token !== winner);
```js
            lotteryBox = lotteryBox.filter(token => token !== winner);

            return winner;
```

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/pick-winners.js
> +        };
```js
        winners.forEach(winner => {
            winnersEmbed.addField(`( ${i + 1} )`, `<@${winner.id}> - ${winner.username}#${winner.discriminator}`);
        });
```

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/pick-winners.js
> +        await message.channel.send(`Empty the lottery box ?`).then(async sentMessage => {
enlève le then, mets un `const sentMessage =` au début

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/pick-winners.js
> +            sentMessage.awaitReactions(reactFilter, { max: 1, maxEmojis: 1, time: 900000 }).then(async collectedReactions => {
15 * MINUTE

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/token-board.js
> -
Remets la ligne stp

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/use-token.js
> +            return message.channel.send(`${trans('model.command.useToken.argError')}`);
Saut de ligne avant
Ne pas avoir de quotes, t'as juste une variable

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/use-token.js
> +        const canApply = await MemberToken.canApply(message.author.id, args[0]);
hasEnoughTokens au lieu de canApply

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/use-token.js
> +        await MemberToken.apply(message.author.id, args[0]).then(async () => {
useTokens au lieu de apply

2021-02-28 21:56 UTC, LilyWonhalf commented on model/command/use-token.js
> +        await MemberToken.apply(message.author.id, args[0]).then(async () => {
await oui mais pas le then

2021-03-01 11:42 UTC, julienChemin commented on model/command/pick-winners.js
> +        };
j'ai besoin de 'i' pour le classement

2021-03-01 13:37 UTC, julienChemin commented on model/command/pick-winners.js
> +        for (let i = 0; i < amountToPick; i++) {
le .map ne ce déclenche pas et winner est remplit avec des "empty items". Je suis resté sur la boucle for

2021-03-01 13:38 UTC, julienChemin commented on model/command/pick-winners.js
> +            lotteryBox = lotteryBox.filter(token => token !== winner);
le .map ne ce déclenche pas et winner est remplit avec des "empty items". Je suis resté sur la boucle for

2021-03-02 01:04 UTC, LilyWonhalf commented on model/command/pick-winners.js
> +        for (let i = 0; i < amountToPick; i++) {
Essaie `const winners = new Array(amountToPick).fill('').map(() => {` alors

2021-03-05 06:25 UTC, LilyWonhalf commented on model/command/pick-winners.js
> +        };
```js
        winners.forEach((winner, i) => {
            winnersEmbed.addField(`( ${i + 1} )`, `<@${winner.id}> - ${winner.username}#${winner.discriminator}`);
        });
```

2021-03-05 06:30 UTC, LilyWonhalf approved these changes
C'est étrange d'avoir une commande qui dit "use tokens", et des variables / méthodes / traductions qui disent "apply tokens". Faudrait que ce soit consistant et qu'on ait "use" partout au lieu de "apply".

Je valide pour l'instant parce que c'est pas bloquant mais si tu pouvais corriger dans une nouvelle PR de la même branche ça serait bien

2021-03-05 06:30 UTC, merged